- name: Проверка статуса UFW на удаленных хостах
  hosts: all
  become: yes  # Используйте sudo для выполнения команд
  tasks:
    - name: Проверка статуса UFW
      command: ufw status
      register: ufw_status

    - name: Вывод статуса UFW
      debug:
        var: ufw_status.stdout
